<?php

return [
    'title' => 'Helpful project docs',
    'labels' => [
        'doc_focus' => 'Doc focus:',
        'doc_coverage' => 'Doc coverage:',
        'doc_baseline' => 'Doc baseline:',
        'seam_source_focus' => 'Seam-source focus:',
        'seam_source_coverage' => 'Seam-source coverage:',
        'seam_source_baseline' => 'Seam-source baseline:',
        'seam_source_posture' => 'Seam-source posture:',
        'seam_source_source_of_truth' => 'Seam-source source of truth:',
        'doc_guide' => 'Doc guide:',
        'doc_posture' => 'Doc posture:',
        'source_of_truth' => 'Source of truth:',
        'reference_seam_bridge' => 'Reference seam bridge:',
    ],
    'copy' => [
        'coverage_suffix' => 'public Galaxy migration references currently linked.',
        'baseline_note' => 'keeps this public Galaxy migration reference inventory aligned.',
        'seam_source_coverage_suffix' => 'Phase 1 seam sources currently documented in',
        'seam_source_baseline_note' => 'keeps that README-level seam-source inventory aligned.',
        'seam_source_source_of_truth_note' => 'remain the readable and implementation anchors for those Phase 1 seam sources.',
        'guide_note' => 'remain the readable anchors for this public Galaxy migration reference trail.',
        'source_of_truth_note' => 'remain the readable and implementation anchors for this public Galaxy migration reference trail.',
        'reference_seam_bridge' => 'keeps the README-level seam-source inventory tied into this broader public Phase 1 reference trail.',
    ],
    'focus' => 'Keep the public Galaxy migration reference trail visible from the landing surface while repo guidance and Phase 1 seams are still moving.',
    'guide' => ['README.md', 'docs/blueprint.md', 'docs/phase-1-plan.md'],
    'source_of_truth' => ['README.md', 'config/landing-docs.php'],
    'posture' => 'public reference inventory stays explicit across the live Galaxy landing trail',
    'items' => [
        [
            'label' => 'OpenClaw docs',
            'href' => 'https://docs.openclaw.ai',
            'external' => true,
        ],
        ['label' => 'README.md'],
        ['label' => 'docs/blueprint.md'],
        ['label' => 'docs/phase-1-plan.md'],
        ['label' => 'docs/phase-1-domain-map.md'],
        ['label' => 'docs/phase-1-foundation-seams.md'],
        ['label' => 'config/landing-foundation.php'],
        ['label' => 'config/phase-1-seam-sources.php'],
        ['label' => 'docs/migration-plan.md'],
        ['label' => 'docs/migration_plan.md'],
        ['label' => 'docs/admin-information-architecture.md'],
        ['label' => 'docs/admin-shell-layering.md'],
        ['label' => 'docs/admin-shell-config-map.md'],
        ['label' => 'docs/decisions.md'],
        ['label' => 'docs/module_mapping.md'],
        ['label' => 'docs/db_schema.md'],
        ['label' => 'docs/api_endpoints.md'],
        ['label' => 'docs/checkpoints/'],
        ['label' => 'docs/analysis/'],
        ['label' => 'docs/qa-test-environment.md'],
        ['label' => 'docs/progress-log.md'],
    ],
];
