<?php

return [
    'focus' => 'Keep the public Galaxy migration reference trail visible from the landing surface while repo guidance and Phase 1 seams are still moving.',
    'guide' => ['README.md', 'docs/blueprint.md', 'docs/phase-1-plan.md'],
    'source_of_truth' => ['README.md', 'config/landing-docs.php'],
    'posture' => 'public reference inventory stays explicit across the live Galaxy landing trail',
    'items' => [
        [
            'label' => 'OpenClaw docs',
            'href' => 'https://docs.openclaw.ai',
            'external' => true,
        ],
        ['label' => 'README.md'],
        ['label' => 'docs/blueprint.md'],
        ['label' => 'docs/phase-1-plan.md'],
        ['label' => 'docs/phase-1-domain-map.md'],
        ['label' => 'docs/phase-1-foundation-seams.md'],
        ['label' => 'config/landing-foundation.php'],
        ['label' => 'config/phase-1-seam-sources.php'],
        ['label' => 'docs/migration-plan.md'],
        ['label' => 'docs/migration_plan.md'],
        ['label' => 'docs/admin-information-architecture.md'],
        ['label' => 'docs/admin-shell-layering.md'],
        ['label' => 'docs/admin-shell-config-map.md'],
        ['label' => 'docs/decisions.md'],
        ['label' => 'docs/module_mapping.md'],
        ['label' => 'docs/db_schema.md'],
        ['label' => 'docs/api_endpoints.md'],
        ['label' => 'docs/checkpoints/'],
        ['label' => 'docs/analysis/'],
        ['label' => 'docs/qa-test-environment.md'],
        ['label' => 'docs/progress-log.md'],
    ],
];
