<?php

return [
    'focus' => 'Keep the current Galaxy admin map, shell layering, checkpoint trail, foundation-seam baseline, and seam-source baseline close while Phase 1 slices are still moving.',
    'guide' => ['README.md', 'docs/blueprint.md', 'docs/phase-1-plan.md'],
    'source_of_truth' => ['README.md', 'docs/blueprint.md', 'docs/phase-1-plan.md', 'docs/phase-1-foundation-seams.md', 'config/phase-1-foundation-seams.php', 'docs/phase-1-access-baseline.md', 'config/phase-1-access-baseline.php', 'docs/phase-1-shop-access-baseline.md', 'config/phase-1-shop-access-baseline.php', 'docs/phase-1-model-skeletons.md', 'config/phase-1-model-skeletons.php', 'docs/phase-1-migration-baseline.md', 'config/phase-1-migration-baseline.php', 'config/phase-1-reference-docs.php'],
    'posture' => 'admin reference inventory stays explicit across the live Galaxy dashboard trail',
    'items' => [
        'README.md',
        'docs/blueprint.md',
        'docs/phase-1-plan.md',
        'docs/phase-1-domain-map.md',
        'docs/phase-1-foundation-seams.md',
        'config/phase-1-foundation-seams.php',
        'docs/phase-1-access-baseline.md',
        'config/phase-1-access-baseline.php',
        'docs/phase-1-shop-access-baseline.md',
        'config/phase-1-shop-access-baseline.php',
        'docs/phase-1-model-skeletons.md',
        'config/phase-1-model-skeletons.php',
        'docs/phase-1-migration-baseline.md',
        'config/phase-1-migration-baseline.php',
        'config/landing-foundation.php',
        'config/phase-1-seam-sources.php',
        'docs/admin-information-architecture.md',
        'docs/admin-shell-layering.md',
        'docs/admin-shell-config-map.md',
        'docs/checkpoints/',
        'docs/progress-log.md',
    ],
];
